#!/usr/bin/env tsx
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

const HERE = dirname(new URL(import.meta.url).pathname);
const ATELIER_ROOT = resolve(HERE, '..');
const REPO_ROOT = resolve(ATELIER_ROOT, '..');
const SRC_ROOT = join(REPO_ROOT, '_packets', 'SPINE', 'skills');
const DST_ROOT = join(ATELIER_ROOT, 'lib', 'anthropic', 'skills');

const HEADER = `// AUTO-GENERATED by scripts/sync-skills.ts — DO NOT EDIT BY HAND.
// Edit the source markdown under _packets/SPINE/skills/ and re-run the sync.
`;

function emit(src: string, dst: string): void {
  const md = readFileSync(src, 'utf-8');
  const escaped = md
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
  const out = `${HEADER}\nexport const content = \`${escaped}\`;\n`;
  mkdirSync(dirname(dst), { recursive: true });
  writeFileSync(dst, out, 'utf-8');
}

function syncDir(srcDir: string, dstDir: string): string[] {
  mkdirSync(dstDir, { recursive: true });
  const written: string[] = [];
  for (const entry of readdirSync(srcDir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      written.push(...syncDir(join(srcDir, entry.name), join(dstDir, entry.name)));
      continue;
    }
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    const tsName = entry.name.replace(/\.md$/, '.ts');
    const dst = join(dstDir, tsName);
    emit(join(srcDir, entry.name), dst);
    written.push(dst);
  }
  return written;
}

function syncCuratorPrompt(): string {
  const src = join(REPO_ROOT, '_packets', 'SPINE', 'CURATOR_PROMPT.md');
  const dst = join(DST_ROOT, '..', 'curator-prompt-source.ts');
  emit(src, dst);
  return dst;
}

const written = syncDir(SRC_ROOT, DST_ROOT);
const curator = syncCuratorPrompt();
written.push(curator);

console.log(`Synced ${written.length} skill modules:`);
for (const p of written) console.log('  ' + p);
