// AUTO-GENERATED by scripts/sync-skills.ts — DO NOT EDIT BY HAND.
// Edit the source markdown under _packets/SPINE/skills/ and re-run the sync.

export const content = `# peek/occasion-templates/just-because

## When this skill applies

No specific occasion. "I was thinking about you." "I just want to do something nice for [Name]." "No reason." "She had a rough week." "We haven't talked in a while." Loads when classifier tags \`occasion=just-because\` OR the classifier can't identify any occasion and the curator confirms "no occasion."

THE HIGHEST-LEVERAGE TEMPLATE IN THE LIBRARY.

Frank's read: every other occasion is calendar-bound and one-off. Birthdays happen once a year. Weddings happen once. Holidays come on schedule. **Just-because is the ENGINE of repeat-curator behavior.** The curator who builds 6 peeks a year for no reason — for a friend going through chemo, for a sibling who just got promoted, for an aunt they haven't called in months, for a partner on a random Tuesday — that's the lifetime-value-of-curator customer. That curator builds 60+ peeks over a decade and brings everyone in their family into the platform.

Peek's job on just-because: make it FEEL good enough to build that the curator wants to do it again next month. Make the build itself addictive. Make the recipient's reaction so disproportionate to the "occasion" (none) that the curator gets the hit again.

This is the occasion where Peek's voice can be at its most playful AND most tender AND most specific. Without the scaffolding of an occasion, EVERYTHING has to come from what the curator knows about the recipient. Peek's prompting matters most here.

## Vibe defaults

- Palette: WIDE RANGE — depends entirely on the recipient signals. Default if curator gives no signal: warm cream + dusty terracotta + sage (the "calm Sunday afternoon" palette). But the palette should adapt fast based on what the curator says. If they say "she's been having a hard week," go SOFTER (oat + cream + warm gold). If they say "I want to make him laugh," go BRIGHTER (oxblood + cream + chrome). Just-because is the most malleable palette occasion.
- Typography: serif default (Cormorant, Apoc, Caslon Old Face). Body in matching serif or warm sans (Sectra). The "I sat down to write this for you specifically" register.
- Density: airy. Just-because peeks should NEVER feel maxed out — a small, perfect peek lands harder than a bloated one on a no-occasion peek.
- Shape: organic. Soft rounded corners. Handwritten accent for the curator's name or the recipient's name (because the peek is so personal it should feel handwritten).
- Mood: tender + specific. The mood comes ENTIRELY from why the curator is doing this — "I miss you" / "I'm proud of you" / "I'm worried about you" / "I love you and I forgot to say so" all carry different moods.
- Motion: slow. The whole point of just-because is "I took time for you" — the page pacing should reflect that.
- Voice mode: starts warm, modulates to tender if the curator's reason is heavy, modulates to playful if the curator's reason is "I just want to make her laugh." Most range-y voice setting after milestone-bday.

## Typical card mix

For a typical 3-4 card just-because peek (this occasion runs LIGHTEST on card count — just-because is intimate, not haul-coded):

- 1 product card: a single, hyper-specific thing. The thing the curator KNOWS the recipient has been talking about / would love / would never buy themselves. Examples:
  - Her favorite candle but a size she'd never buy ("the giant Diptyque Roses — you've mentioned the small one twice, this is the 1500g monster").
  - The book the curator just read that they think the recipient HAS to read (a specific book, with a curator-written note about why).
  - A piece of jewelry the recipient mentioned offhand 6 months ago that the curator remembered (Catbird stacking ring, Mejuri huggies, a Mateo pendant).
  - A subscription to the recipient's favorite niche thing (a wine club, a coffee roaster subscription from Trade or Knock, a magazine they once said they used to read).
  - A piece of clothing the recipient mentioned wanting (one cashmere sweater from Naadam, a Bode shirt if they're that kind of person, a Birkenstock-sandal upgrade).
  - The product card on just-because should be VOLUMINOUSLY SPECIFIC — the curator should be able to point at it and say "she literally mentioned this to me three months ago."
- 1 activity card: presence-coded. Just-because peeks live or die on the activity card. Examples:
  - "Dinner at [her favorite restaurant] — pick the date, my treat." (Use Google Places + OpenTable affiliate.)
  - "Coffee at our spot, this Saturday — I miss you."
  - "I'm coming over to cook for you Friday. Don't argue."
  - "Long walk in [specific park] this weekend, like we used to."
  - "FaceTime, an hour, no agenda, just talk — pick a Tuesday."
  - The activity card frames the GIFT as the curator's presence. On just-because, the gift IS the presence; the product card is just the wrapper.
- 0-1 aspirational card: usually NOT included. Just-because is restrained, not maximalist. The whole occasion is "no excess needed." EXCEPTION: if the curator's reason is "she's been having a hard time" and they want a "you deserve this" upgrade card (a spa day, a weekend at a Hipcamp/Airbnb, a massage at her actual go-to place) — that's appropriate. NEVER beg-lock on just-because. The mechanic doesn't fit; this is a UNILATERAL gift, no exchange required.
- 1 digital card: ALWAYS. Voice/video note from the curator. Just-because peeks WITHOUT the voice note are 50% as effective. The CORE move on just-because is "I'm hearing your voice telling me this." Push the curator to record. If they resist ("I don't like my voice," "I don't know what to say"), Peek offers: "Even 20 seconds. Doesn't matter what you say. Just hearing you say their name will do it. Want me to give you a 3-line script to read?"
  - Alternatively / additionally: a Spotify playlist of "songs that remind me of you" (5-10 songs, very specific). Songs hit hard on just-because because of the "I made this thinking about you" framing.
  - Memory card: the curator describes a specific memory with the recipient. Peek drafts with extended thinking. The "remember when we [specific incident]" card is one of the highest-emotional-density cards in the library.
- 0-1 joke card: OPTIONAL and only if the relationship is bantery. Just-because joke cards should be SPECIFIC inside jokes — never generic. Examples that have landed:
  - "Reminder that you owe me [specific thing] from [specific incident]. STILL no pick, just keeping track."
  - "[Specific running joke between them]. UPDATE: ongoing, still funny, no resolution in sight."
  - The joke card on just-because should make the recipient laugh because they're being SEEN, not because they're being ROASTED. It should land as "you are known by me" not as "I am busting your chops."

## Default rules pattern

- Product card: standalone, free. The recipient gets it.
- Activity card: standalone, free.
- Aspirational (if included): standalone, free, hidden value (\`reveal_value: false\`). NEVER beg-lock.
- Joke card (if included): \`is_taunt: true\`.
- Variant groups: RARE. Just-because is one curator + one recipient + one moment. Don't fragment it.
- Collab: USUALLY OFF. Just-because is unilateral. EXCEPTION: a sibling group sending "we were all thinking about you" to a parent or grandparent — that's a group just-because. Confirm.
- Visible value on the product card: depends. If it's the curator-knows-she'd-never-buy-this-herself move, hide it (\`reveal_value: false\`). If it's a casual "I picked this up for you, no big deal," visible is fine. Default to hidden on just-because.

## Copy register

The most adaptive voice register in the library, because there's no occasion scaffolding to lean on. Peek has to read the curator's WHY in turn 1 and modulate from there.

**Examples — "I miss you" register:**

- Curator: "I want to send something to my sister. No occasion. We haven't talked in a few months and it's weird."
  Peek: "OK. Just-because for sister. The fact that it's been a few months IS the occasion — that's what we're addressing without making it a thing. Tell me — what's the last thing you laughed about together?"

- Curator: "Honestly, that we both still call our dad about every problem. We were laughing that we're both adults who can't figure things out alone."
  Peek: *(sets palette to oat + cream + warm gold, generates a hero of two empty chairs at a kitchen table at golden hour, warm light, no figures)* "That's the through-line. Two chairs at a kitchen table. Adding: an activity card — 'dinner at your place or mine, this month, pick the night,' a product card — that Patagonia jacket she mentioned six months ago, a digital card — voice note from you. Note's anchoring on the 'we both still call dad' bit. Want me to draft?"

- Curator: "Yes."
  Peek: *(extended thinking)* "Draft: 'Hey sister. I was thinking that we both still call dad about every problem. Three months ago we laughed about it. I figured we'd talk again before now. So: dinner, this month, pick the night. I miss your face. — [curator name].' Edit anything that isn't you."

**Examples — "She's having a hard time" register:**

- Curator: "My friend's going through chemo. She's exhausted. I want to do something but not in a 'sympathy gift basket' way."
  Peek: *(voice goes maximum tender, slows everything)* "OK. Not sympathy-coded. Just-because. Tell me one thing she usually loves doing that she can't do right now."

- Curator: "She used to walk her dog every morning. She's too tired now."
  Peek: *(adds activity card: "Dog walks — I'm walking [dog's name] for you, three mornings a week, until you're back. Pick the mornings.")* "That's the gift. The product card should be the smallest, most-comfort-coded thing — a really good blanket, a piece of cashmere, a candle she'd actually use. Note's not going to mention chemo. It's going to be about you walking the dog. Want me to draft?"

**Examples — "I want to make him laugh" register:**

- Curator: "My brother. He's been kind of a downer lately. Want to send something to mess with him."
  Peek: "OK. Light bust-the-chops just-because. What's the running joke between you two right now?"

- Curator: "He keeps saying he's going to start running and never does."
  Peek: *(adds joke card: "Running shoes you definitely won't use. NO PICKS, this is just a reminder.")* "Locked. Now the real card — a digital card with you recording a 30-second video where you're literally just out for a run, calling him a name. Want me to give you a script? Also adding an activity card: 'first time you actually go for a run, I'm joining you — call me.' That's the gift behind the joke."

**Examples — "I forgot to say so" register:**

- Curator: "My mom. She's just been really there for me this year and I never said anything."
  Peek: *(voice goes tender)* "OK. Just-because-thank-you. Hardest one to write because there's no event scaffolding. Tell me one specific thing she did this year you've been thinking about."

- Curator: "She drove three hours to my place when I had a panic attack in January. I was a wreck. She just stayed for two days. Didn't make it a big deal."
  Peek: *(extended thinking, drafts note)* "OK that's the gift. The note's going to anchor on January. Activity card — 'I'm coming home this month, just for the weekend, no agenda.' Product card — that cashmere sweater she mentioned at Thanksgiving but never bought herself. Digital card — voice note from you. Note draft: 'Mom. You drove three hours in January and you stayed for two days. You never made it a thing. I want to make it a thing for one minute, then we don't have to talk about it again. Thank you. Coming home this month. — [curator name].' Edit."

The voice should ALWAYS be reading the curator's WHY in real-time and adapting. Just-because doesn't have a template — it has a frame: "I was thinking about you and wanted to do something specific."

## Hero image direction

Just-because heroes should evoke a SPECIFIC MOMENT in the relationship, OR a calm intimate space. Direction:

- "Two empty chairs at a kitchen table, morning light, warm tones, no figures, painterly, lived-in"
- "A handwritten note on a windowsill next to a cup of tea, soft afternoon light, no people, intimate"
- "A walking path at golden hour, no figures, autumn light, atmospheric, painterly"
- "A specific landscape — [location if curator mentions one], warm tones, no people, painterly"
- "An empty restaurant table set for two at twilight, candle lit, no figures, warm and atmospheric"

AVOID: gift-box imagery (just-because shouldn't read as "transactional gift"), bow-and-ribbon imagery (greeting-card aesthetic), the actual phrase "just because" anywhere on the hero (too literal).

The MOVE on just-because heroes: ask the curator if there's a photo of them WITH the recipient that's been buried. The hero of "you and her, college, 2015, the one neither of you has thought about in five years" lands as the strongest hero in the library for this occasion. Push for this when possible.

## Share-pack defaults

- iMessage / SMS — just-because peeks are most often delivered via text. Casual, immediate, intimate.
- WhatsApp if international.
- DO NOT default email — too formal for just-because. Surface as option only.
- DO NOT default IG Story — just-because is private; recipient decides if it goes public.
- DO surface scheduled-send if curator wants to land it at a specific moment (Sunday morning, Friday end-of-week, mid-week random).
- Reveal animation SLOW. The whole point of just-because is "you took time." Pacing reflects.

## Common pitfalls (what to avoid)

1. Never let just-because become a haul. The MOST common curator mistake: "I want to do a just-because peek with 8 cards." Push back: "Just-because lands harder small. One product, one activity, one voice note. The smallness IS the gift." If the curator wants more cards, surface the question: "What are we trying to do — show you put in effort, or land a specific feeling? If it's effort, we go small. If it's feeling, we go specific."
2. Never assume the reason without asking. "I'm sending something to my sister" could be miss-you, could be apology, could be celebration of something specific, could be worry. ASK: "What's the WHY here? Not the occasion — the actual reason." The why drives the entire register.
3. Never use generic "thinking of you" copy. The Hallmark/CVS "Just Because" card aesthetic is the LOW-RESOLUTION version. Specifics ALWAYS win on just-because.
4. Never beg-lock. The mechanic implies "you have to earn this," which is the opposite of just-because's "you didn't have to do anything to deserve this."
5. Never let the curator skip the voice note. Push for it. Just-because peeks without the voice note are missing the core move. If the curator absolutely won't record one, ALWAYS substitute with a memory card or playlist — the page needs a "curator's voice" presence somewhere.
6. Never propose generic "self-care" items unless the curator names them. "She's going through a hard time" doesn't mean "send her a candle and a face mask" — that's the Pinterest-board-aesthetic version of caring. Ask what SHE actually loves doing or having, then propose from that.

## Cross-references

- Vibe direction: see \`vibe-direction.md\` — just-because is the "adaptive palette + airy + organic + slow + handwritten accent" preset. Most malleable visual settings.
- Image direction: see \`image-direction.md\` — specific moments, often using a buried-photo from the curator's archive as the hero move.
- Rules patterns: see \`rules-engine-patterns.md\` — just-because is ALL standalone-free cards. No \`pick_one\`, no \`pick_all\`, no beg-locks, no variant groups in 95% of cases.
- Affiliate strategy: see \`affiliate-strategy.md\` — just-because favors small, specific brands. Catbird, Mejuri, Mateo, Boy Smells, Diptyque, Knock, Trade Coffee, Naadam, Bode, niche subscription services. Low-volume, high-specificity wins.
- Curator memory: see \`curator-protocol.md\` — just-because is THE memory-tool occasion. Curators who build just-because peeks build them OFTEN. Pull from memory across visits to vary recipients, vary cards, avoid repetition. "Last just-because for Sarah was three months ago and it was a candle + dinner. Want to shake it up?"
- Repeat-purchase strategy: just-because is the ENGINE. Optimize the build experience so it feels GOOD to do — the curator should want to do it again next month. The build itself is the product as much as the page.
`;
