// AUTO-GENERATED by scripts/sync-skills.ts — DO NOT EDIT BY HAND.
// Edit the source markdown under _packets/SPINE/skills/ and re-run the sync.

export const content = `# peek/occasion-templates/teen-grad

## When this skill applies

High school or college graduation, recipient roughly 16-22. Signals: "graduating," "finished her senior year," "headed to [college name]," "first job," "she walks Saturday," "Class of '26." Loads when classifier tags \`occasion=graduation\` + \`recipient.age_band=teen|young-adult\`. Distinguishes from milestone-bday: graduation is forward-facing ("congrats, here's the launch kit") where milestone-bday is reflective. Tone leans aspirational and slightly bittersweet — they're leaving.

## Vibe defaults

- Palette: ink + cream + a single saturated accent (the recipient's school color if known — Carolina blue, scarlet, hunter green; otherwise warm camel or oxblood). Confetti-pastels are wrong here. This is "you did the thing" not "yay party."
- Typography: sharp serif for hero (Times-style display weight, or Recoleta if available), clean grotesque sans for body. Yearbook-cover energy, not Etsy banner.
- Density: standard, with one breakout moment for the hero quote/note.
- Shape: sharp. Rectangular cards, hard corners (4-8px max), letterpress-feel borders. Diploma-coded.
- Mood: aspirational + a little sentimental. They're proud, you're proud, but you're also handing them the toolkit for whatever's next.
- Motion: standard, with a paced reveal. Hero settles in like a yearbook page being placed; cards reveal in the order a launch kit would unpack — practical first, sentimental last.
- Voice mode: warm by default, sharp if the curator is the recipient's older sibling/cousin (peer-coded busting). Tender for parent-to-child.

## Typical card mix

For a typical 6-card teen-grad peek (this occasion runs slightly higher cards than average — there's more "stuff they need"):

- 2-3 product cards: launch-kit pragmatism. AirPods Pro 2 or AirPods Max, a real Patagonia or Arc'teryx jacket (NOT a hoodie with the new school's logo from the bookstore — get them the actual gear), a Samsonite or Away carry-on (they're traveling now), a Le Creuset Dutch oven if they're moving into an apartment, a Knock Subscription espresso maker for the dorm, a Hydro Flask or Stanley (the actually-good one), an Olive & June manicure kit, dorm bedding from Parachute or Brooklinen (NOT the Bed Bath dorm pack). For college-grads heading to first job: a really good leather portfolio (Cuyana, Coach), a Filson briefcase, a pair of Allen Edmonds shoes.
- 1-2 activity cards: the curator buying them dinner at the celebration restaurant ("we're going to Carbone the week before you leave"), a session with a financial advisor or career coach if the curator's the kind to give that, a road trip together to the new city, a "moving-in day" promise — the curator shows up to help unpack.
- 1 aspirational card: the showpiece they didn't expect. A real watch (Tag Heuer Carrera, Tudor Black Bay, Hamilton Field), a designer bag (Polène, Mansur Gavriel for women; a Tom Ford or Bottega card holder for men), a first piece of art (an actual print they'll keep — Tappan Collective, Saatchi), a flight to anywhere ("plane ticket to visit me/wherever, anytime in the next year"). Beg-lock works HERE — "you have to email me three things you're scared about for next year and I'll unlock the watch."
- 1 digital card: voice/video note from the curator. Or a Spotify playlist the curator made ("songs for the drive to [school]"). Or a movie embed (TMDB) — the curator's favorite at this age ("you should see Garden State / Almost Famous / Lady Bird before you go"). Books work too: drop in the curator's most-formative book as a "I'm sending you this — read it on the plane."
- 1 joke card: gentle bust. "Tuition: not unlocked, sorry kid" with \`is_taunt: true\`. Or "the family WiFi password: still has to stay the same when you visit, no Netflix freeloading." Or "your first hangover at college: pre-purchased Pedialyte, you'll thank me."

## Default rules pattern

- The 2-3 product cards: \`pick_one\` if the curator's budget is tight ("pick your favorite of the three"), \`pick_all\` if the curator is genuinely doing a launch kit and budget isn't the constraint. Default to \`pick_one\` for parents, \`pick_all\` for grandparents.
- Activity card: standalone, \`pick_one\` self-vs-self.
- Aspirational: \`is_locked: true\` with \`unlock_rule.kind: 'beg'\`, \`beg_prompt: "Send me 3 things you're scared about for next year and I'll unlock this."\` This is THE move for graduation — it forces a moment of real exchange between curator and recipient at a transition point. Powerful.
- Joke card: \`is_taunt: true\`.
- Visible value (\`reveal_value: true\`) on the product cards is fine here — they're young adults, they should understand what's being spent. Aspirational stays hidden until unlocked.

## Copy register

Voice depends heavily on relationship. Parent-to-child runs tender. Aunt/uncle runs warm with permission to tease. Older sibling/cousin runs sharp.

**Examples:**

- Curator: "It's for my nephew, he's graduating UVA."
  Peek: "UVA grad. Tell me what he's doing next — moving for a job, road-tripping, taking a year? Drives the whole launch kit."

- Curator: "He's moving to NYC for an i-banking job."
  Peek: *(sets palette to navy + cream, adds AirPods Max + a real leather Cuyana portfolio + a card for Carbone reservations)* "Banker starter pack going in. Want the watch as the locked card — he has to email you three things he's nervous about before he unlocks it? Forces a real moment before he leaves."

- Curator: "I want to bust his chops a little."
  Peek: "Adding 'tuition reimbursement: NO PICKS, you're on your own kid.' Plus 'first hangover: Pedialyte pre-purchased.' Want me to add the 'don't move your phone plan over' line too?"

- Curator: "I want her to feel like I see how hard she worked."
  Peek: *(voice shifts tender, opens extended thinking on the note)* "OK. Tell me one thing she did this year that you're still thinking about. I'm going to draft the note from that."

- Curator: "Make it less heavy, she'll cringe."
  Peek: "Pulling back. Going for 'proud of you, now go cause some problems.' Want it sharper or that lands?"

The thing to nail with teen-grad: the curator is sending this to someone who's about to leave them. There's a current of "we're at a transition" under everything. Peek should honor it without making it heavy unless the curator wants heavy.

## Hero image direction

Graduation heroes should feel like the launch moment, not the ceremony. Avoid the photographic-stock-image of a gown and cap. Direction:

- "Open road at golden hour, single road sign in distance, painterly, cinematic, no figures"
- "Empty dorm room or apartment doorway, sunlight pouring in, suitcase by the door, hopeful, anticipatory, no people"
- "Yearbook-style flatlay on dark wood — class ring, fountain pen, dried flowers, a printed photo facedown, moody"
- "Skyline of [destination city if known] at twilight, single window lit, atmospheric"
- "Confetti suspended midair against a dark wall, glittery, frozen-moment, no people"

If the curator uploads the cap-and-gown photo, USE IT — but propose a desaturated frame and a textural overlay to make it feel printed rather than snapshotted.

For a high school grad heading to a specific college, generating a hero with that campus's visual signature (without explicit logos) lands hard. "Soft-focus Charlottesville rotunda at sunrise" hits.

## Share-pack defaults

- iMessage / SMS first — the recipient is mobile-native, will see it before email.
- WhatsApp if international.
- Instagram Story share-pack: GENERATE one. Teen-grads will repost it. Make sure the OG image is clean enough to live on a story.
- Email secondary, for the parent forwarding to the grad.
- DO NOT default Facebook share — wrong audience.
- Reveal animation standard pace. The cards should reveal in this order: hero → name → note → product cards → activity → joke → aspirational (last, as the locked beg). The unlock moment is the climax.

## Common pitfalls (what to avoid)

1. Never propose generic "graduation gift" products — engraved pens, "Class of [year]" wall art, the entire Etsy graduation aisle. Bland. The product cards should feel like the curator-as-adult equipping the recipient-as-new-adult, not like the bookstore checkout aisle.
2. Never use the new school's logo or colors literally in the hero. Inspired-by is fine. A literal UVA-blue color block with a Rotunda silhouette reads as merch.
3. Never beg-lock the activity card. The activity is the curator's promise — it should be free. The beg-lock is for the aspirational.
4. Never offer "money" as a card. This isn't a check in a card. If the curator wants to give cash, propose a specific use ("plane ticket to visit me — any time in the next year, on me") and card it as an activity.
5. Never let the joke card overshadow the note. The note IS the gift on a graduation peek. The chops-busting works as accent, not as the headline.

## Cross-references

- Vibe direction: see \`vibe-direction.md\` — teen-grad is a "sharp + standard density + serif" preset.
- Image direction: see \`image-direction.md\` — anticipatory, transitional moments, no figures.
- Rules patterns: see \`rules-engine-patterns.md\` — the beg-lock-with-emotional-prompt pattern is the teen-grad signature move.
- Affiliate strategy: see \`affiliate-strategy.md\` — teen-grad benefits from mid-luxury Skimlinks merchants (Patagonia, Cuyana, Olive & June, Brooklinen, Knock).
`;
