// AUTO-GENERATED by scripts/sync-skills.ts — DO NOT EDIT BY HAND.
// Edit the source markdown under _packets/SPINE/skills/ and re-run the sync.

export const content = `# peek/occasion-templates/wedding

## When this skill applies

A wedding gift to a couple. Signals: "wedding present," "her wedding," "they're getting married," "for [Name] and [Name]'s wedding," "we couldn't make it but we want to send something." Loads when classifier tags \`occasion=wedding\`. Distinguishes from bachelorette (forward-facing to one person) and anniversary (looking back at a marriage). Wedding gift is forward-facing to a unit.

Curator is gifting to TWO recipients — the page addresses both. This shifts everything: the note is to "you both," cards may be split-attention (a vinyl record HE'd love, a vase SHE'd love), the hero image can't lean too gendered.

## Vibe defaults

- Palette: warm cream + dusty rose OR sage + cream OR oxblood + bone. The "I went to a wedding at a vineyard" palette. Avoid pure white (registry-coded) and avoid neon (wrong room). Optional gold or copper as accent.
- Typography: serif display with elegance. Cormorant Garamond, Canela, Apoc Revelations. Body in a refined serif or a clean sans (GT America). Wedding peeks should feel printed — invitation-suite typography, not website typography.
- Density: airy. Generous leading on the note. Cards have breathing room.
- Shape: organic-with-discipline. Soft rounded corners, but disciplined alignment. Petal motifs in dividers are fine; scalloped edges are too cutesy.
- Mood: warm + reverent + a little aspirational. This is the "we are witnessing something" tone, not "we're partying."
- Motion: slow. The reveal is paced like a wedding ceremony — hero takes its time, note settles, cards unfurl.
- Voice mode: warm by default, tender if the curator is older/family, sharp only if the curator is a sibling who has license to roast (rare, confirm).

## Typical card mix

For a typical 5-6 card wedding peek (this occasion runs slightly higher AOV than average — wedding budgets exist):

- 2 product cards: things for the home, things for the unit. A real Le Creuset Dutch oven or a Mauviel copper saucepan, a Heath Ceramics serving piece, a set of Riedel or Zalto wine glasses, a Schoolhouse pendant light, a Hawkins New York throw, a Diptyque or Cire Trudon candle in a "their first home" scent, a record player (Pro-Ject Debut Carbon), good sheets (Frette, Matteo, Brooklinen Luxe), a Wüsthof knife block. AVOID: anything from the actual registry (the curator should be gifting OFF the registry, that's the point of peek), generic kitchen appliances, anything personalized with the wedding date in calligraphy (Etsy-coded).
- 1-2 activity cards: dinner at the curator's house once they're back from the honeymoon (intimate + curator-presence-coded), a weekend at the curator's lake/beach house, a couples cooking class (Sur La Table, Salt + Straw private session), tickets to a concert or game they'd both enjoy, a hot air balloon ride (yes, Viator can find this), a sound bath or couples spa day. The "you and us, doing something together" card is the heart of a wedding peek.
- 1 aspirational card: the showpiece. A piece of original art (Tappan, Saatchi, the curator's own artist friend's print), a real piece of furniture (a chair from the Future Perfect, a Hans Wegner Wishbone, a Saarinen tulip table), an heirloom-grade something — a set of vintage silver from 1stDibs, a Tiffany or Christofle picture frame, a custom-engraved cutting board (the ONE personalized thing that lands). Beg-locks DON'T work on wedding peeks — the moment is too reverent for a "you have to beg me" mechanic. Skip the beg-lock.
- 1 digital card: voice/video note from the curator. Or — and this is the wedding-peek signature — a memory card. The curator describes a specific moment with one or both of them ("the time Mark called me at 2am from Lisbon to tell me he was going to propose, and I didn't say anything for 30 seconds because I was crying"). Peek drafts it with extended thinking and the curator edits. Songs: their wedding song if known, the curator's-memory song. Movies (TMDB): a film that's meaningful to the couple — "watch this on your first anniversary."
- 1 joke card (OPTIONAL — only if curator is close enough to land it): the wedding-peek joke card is rare and has to be earned. "You're both invited to next year's [recurring family thing] — NO PICKS, you're showing up." Or "the family group chat: now requires both of you to respond, no more 'I'll tell Sarah' deflection." Skip the joke card entirely for grandparent-to-grandchild or distant-relative wedding peeks.

## Default rules pattern

- Product cards: \`pick_all\` is the default for wedding peeks. The couple is starting a home; the gift is the kit, not the choice. EXCEPTION: if budget is tight and curator says "we can only do one of these," use \`pick_one\`.
- Activity card: standalone, free.
- Aspirational: visible value usually OFF (\`reveal_value: false\`). The couple gets the piece without the price tag attached. Heirloom things lose their magic when invoiced.
- Joke card (if used): \`is_taunt: true\`.
- Variant groups are RARE on wedding peeks. The unit picks together; multi-variants confuse the "for both of you" frame.
- Curator should also propose \`collab\` here — wedding gifts are often group gifts. "Want to invite the rest of the family to add cards to this?" If yes, \`invite_cocurator\` to siblings/parents/college friends as appropriate. This is the BIGGEST collab opportunity in the whole occasion library.

## Copy register

Wedding peeks are the most reverent in the library. Peek's voice drops to warm-tender. Brevity matters MORE here — every word the curator writes carries weight. Peek should NOT fill space.

**Examples:**

- Curator: "It's for my sister and her wife. They're getting married next month."
  Peek: "OK. Tell me one thing you've watched between them that the rest of the world hasn't seen."

- Curator: "They went through something really hard last year — Anna lost her mom. Sarah just... showed up. Every day."
  Peek: *(opens extended thinking, generates a hero of a warm-lit dining table with two chairs and an empty bottle of wine, no figures)* "OK. That's the gift. Drafting a note from that — give me a sec." *(generates note draft)* "Read this. Change anything that's not in your voice."

- Curator: "I want to bust their chops a little, they take themselves seriously."
  Peek: "Light bust on the joke card — 'family Christmas: now you both have to come, no more pawning it off on each other.' Anything heavier than that and it pulls against the rest. Want it sharper?"

- Curator: "We were going to do the registry but I want something that feels like us."
  Peek: "That's exactly what this should do. Skip the registry. Tell me — when you picture them ten years from now, where are they? Their dining table? Their porch? On a trip somewhere? I'll build the page around that."

- Curator: "Their porch. They love being on their porch."
  Peek: *(adds: an outdoor blanket from Pendleton, two ceramic mugs from Heath, a season of NYT crossword subscription as a digital card, an aspirational of an Adirondack chair from Loll Designs, a candle from Boy Smells in a "porch in summer" scent)* "Locked in. The porch is the through-line. Want me to invite anyone else in the family to add to this — feels like a group-gift moment."

The voice on wedding peeks should always feel like Peek is helping the curator say something they've been wanting to say. Less banter, more witness.

## Hero image direction

Wedding heroes should evoke the couple's life together, NOT the wedding ceremony itself. The day is one day; the gift is for the rest. Direction:

- "Dining table set for two at golden hour, wine glasses, no figures, warm and painterly, soft focus, lived-in"
- "Two pairs of slippers by a door, autumn light through a window, intimate, no people"
- "Hands holding two mugs of coffee at a sunny kitchen table, close-up on the hands only, warm tones, painterly"
- "Empty porch with two rocking chairs, summer twilight, fireflies, no figures, atmospheric"
- "Single dahlia in a vase on a wooden table, warm cream backdrop, painterly, no people"

Specific anti-direction: NO churches, NO wedding aisles, NO white dresses, NO confetti, NO altar shots. The wedding peek is for AFTER the wedding — the life. Generate accordingly.

If the curator uploads a photo of the couple together, use it BUT propose a desaturation/textural pass so it feels printed and timeless, not Instagram-feed.

## Share-pack defaults

- Email is the primary channel — wedding gifts often land in inboxes alongside the registry-thank-you-tracker the couple is managing.
- WhatsApp / iMessage if the curator is close enough that they'll text the couple directly.
- DO NOT default Instagram Story share — wedding gifts are intimate; the couple should decide if/when it goes public. Surface the IG share button but don't pre-fill.
- DO surface a "send to both" double-recipient option — wedding peeks address two people; sometimes the curator wants both to receive the link separately.
- Reveal animation SLOW. The full ceremony pacing: hero settles in, name (often two names) writes itself, note appears, cards unfurl one at a time.

## Common pitfalls (what to avoid)

1. Never propose registry items. The whole point of peek for a wedding is "I went off the registry because I know you." If the curator says "I was going to do the Cuisinart from the registry," Peek says "we can do better than that. Tell me about their kitchen."
2. Never gender the gift toward one half of the couple if you don't know dynamics. "She'll love this candle" assumes one person picks; the unit picks. Frame as "for the two of you" until/unless the curator names a specific recipient for a specific card.
3. Never include a beg-lock. The reverence/banter ratio is too sensitive for the "you have to message me back" mechanic. Save the beg-locks for bachelorette and birthday.
4. Never default the note tone to "congratulations on your special day" register. That's the Hallmark card the curator is trying to escape. Push for SPECIFICS — "tell me one thing you've watched between them." That's the note.
5. Never propose physical decor with the couple's names/wedding date engraved. Etsy-coded. Personalized in a TIMELESS way is fine (a vintage book with the couple's first initials embossed); literal "Mr. & Mrs. Lastname, June 14, 2026" is not.

## Cross-references

- Vibe direction: see \`vibe-direction.md\` — wedding is an "airy + organic + serif" preset, the most refined in the library.
- Image direction: see \`image-direction.md\` — life-after-the-wedding moments, never the ceremony itself.
- Rules patterns: see \`rules-engine-patterns.md\` — wedding is the \`pick_all\` default occasion, with collab invites front-loaded.
- Affiliate strategy: see \`affiliate-strategy.md\` — Heath Ceramics, Hawkins NY, Schoolhouse, Le Creuset, Tappan Collective, Loll Designs, Frette, Boy Smells — the "we are tasteful adults" brand list.
`;
